long ans = 2 * k * k + 2 * k + 1;
            
            #include<bits/stdc++.h>
            using namespace std;
            int main()
            {
             long int t,n,m,d;
             cin>>t;
             while(t--)
             {
              cin>>n>>m;
              for(int i=0;i<n;i++)
                for(int i=0;i<m;i++)
                  cin>>man[i][j];
 
               for(int i=0;i<n+m-2;i++)
                for(int i=0;i<m;i++)
                  cout<<2*d*d+2*d+1 









             }




            }